export default {
  MAX_ATTACHMENT_SIZE: 5000000,
  apiGateway: {
    REGION: "{AWS_REGION}",
    API_URL: "{API_GATEWAY_EXECUTION_URL}",
  },
  cognito: {
    REGION: "{AWS_REGION}",
    USER_POOL_ID: "{AWS_COGNITO_USER_POOL_ID}",
    APP_CLIENT_ID: "{AWS_COGNITO_CLIENT_ID}",
    IDENTITY_POOL_ID: "{AWS_COGNITO_IDENTITY_POOL_ID}"
  }
};